apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"fake-webhook:latest","namespace":"admin-devspaces"},"fieldPath":"spec.template.spec.containers[?(@.name==\"fake-webhook\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: fake-webhook
    app.kubernetes.io/component: fake-webhook
    app.kubernetes.io/instance: fake-webhook
  name: fake-webhook
  namespace: admin-devspaces
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: fake-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: fake-webhook
    spec:
      containers:
      - env:
        - name: QUARKUS_HTTP_SSL_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/ssl/tls.crt
        - name: QUARKUS_HTTP_SSL_CERTIFICATE_KEY_FILE
          value: /var/run/secrets/kubernetes.io/ssl/tls.key
        - name: QUARKUS_HTTP_SSL_PORT
          value: "8443"
        image: image-registry.openshift-image-registry.svc:5000/admin-devspaces/fake-webhook@sha256:5abd8a2a12a34c83b17d387a0526f03eb72c38c9ef207b2441ddc29da18241b0
        imagePullPolicy: IfNotPresent
        name: fake-webhook
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/ssl
          name: fake-webhook-https
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fake-webhook-https
        secret:
          defaultMode: 420
          secretName: fake-webhook-https
